# coding: utf-8

"""
Nncof_EventsSubscription

Nncof_EventsSubscription Service API.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.individual_ncof_event_subscription_transfer_api import (
    router as IndividualNCOFEventSubscriptionTransferApiRouter,
)
from openapi_server.apis.ncof_event_subscription_transfers_api import (
    router as NCOFEventSubscriptionTransfersApiRouter,
)
from openapi_server.apis.individual_ncof_events_subscription_api import (
    router as IndividualNCOFEventsSubscriptionApiRouter,
)
from openapi_server.apis.ncof_events_subscriptions_api import (
    router as NCOFEventsSubscriptionsApiRouter,
)

from openapi_server.apis.nwdaf_events_notifications_api import (
    router as NWDAFEventsNotificationsApiRouter,
)

from openapi_server.config.app_config import AppConfig, load_config

CONFIG_FILE_PATH = "ncof_server.yaml"

# 설정 로드
app_config: AppConfig = load_config(CONFIG_FILE_PATH)

app = FastAPI(
    title="Nncof_EventsSubscription",
    description="Nncof_EventsSubscription Service API.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. ",
    version="1.0.0",
)

PREFIX = "/ETRI_INRS_TEAM/NCOF_Nncof_EventSubscription/1.0.0"
PREFIX_NOTIFICATIONS = "/ETRI_INRS_TEAM/Nsmf_EventExposure/1.0.0"

app.include_router(IndividualNCOFEventSubscriptionTransferApiRouter)
app.include_router(IndividualNCOFEventsSubscriptionApiRouter, prefix=PREFIX)
app.include_router(NCOFEventSubscriptionTransfersApiRouter)
app.include_router(NCOFEventsSubscriptionsApiRouter, prefix=PREFIX)
app.include_router(NWDAFEventsNotificationsApiRouter, prefix=PREFIX_NOTIFICATIONS)

print(
    r"""
    _   _  ____ ___  _____
    | \ | |/ ___/ _ \|  ___|
    |  \| | |  | | | | |_
    | |\  | |__| |_| |  _|
    |_| \_|\____\___/|_|
    """
)
