# coding: utf-8

"""
Nncof_EventsSubscription

Nncof_EventsSubscription Service API.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.individual_ncof_event_subscription_transfer_api import (
    router as eventSubscriptionTransferApiRouter,
)
from openapi_server.apis.ncof_event_subscription_transfers_api import (
    router as eventSubscriptionTransfersApiRouter,
)
from openapi_server.apis.individual_ncof_events_subscription_api import (
    router as eventsSubscriptionApiRouter,
)
from openapi_server.apis.ncof_events_subscriptions_api import (
    router as eventsSubscriptionsApiRouter,
)

from openapi_server.apis.nwdaf_events_notifications_api import (
    router as eventsNotificationsApiRouter,
)

from .config.app_config import app_config

app = FastAPI(
    title="Nncof_EventsSubscription",
    description="Nncof_EventsSubscription Service API.   © 2025, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. ",
    version="1.0.0",
)

NOTIFICATION_PREFIX = app_config.notification_prefix
SUBSCRIPTION_PREFIX = app_config.subscription_prefix

app.include_router(eventSubscriptionTransferApiRouter)
app.include_router(eventSubscriptionTransfersApiRouter)
app.include_router(eventsSubscriptionApiRouter, prefix=SUBSCRIPTION_PREFIX)
app.include_router(eventsSubscriptionsApiRouter, prefix=SUBSCRIPTION_PREFIX)
app.include_router(eventsNotificationsApiRouter, prefix=NOTIFICATION_PREFIX)

print(
    r"""
    _   _  ____ ___  _____
    | \ | |/ ___/ _ \|  ___|
    |  \| | |  | | | | |_
    | |\  | |__| |_| |  _|
    |_| \_|\____\___/|_|
    """
)
